Initial working commit

diff --git a/opendevin b/opendevin
--- a/opendevin
+++ b/opendevin
@@ -1,9 +1,10 @@
 #!/bin/bash
 
+# Shell configuration
 shopt -s extglob
 set -Eeo pipefail
 
-# Set global variables
+# Global variables
 DEBUG=${DEBUG:-false}
 ACTION=${ACTION:-}
 SUBACTION=${SUBACTION:-}
@@ -15,10 +16,16 @@ CSCRIPT_DIR=$(dirname "$0")
 
 # Colors
 C_DARK_WHITE="\033[0;30m"
-C_WHITE="\033[0;37m";       C_YELLOW="\033[0;33m";
-C_RED="\033[0;31m";         C_BLUE="\033[0;34m";            C_GREEN="\033[0;32m"
-C_BOLD_WHITE="\033[1;37m";  C_BOLD_YELLOW="\033[1;33m";     C_BOLD_RED="\033[1;31m"
-C_BOLD_BLUE="\033[1;34m";   C_BOLD_GREEN="\033[1;32m"
+C_WHITE="\033[0;37m"
+C_YELLOW="\033[0;33m"
+C_RED="\033[0;31m"
+C_BLUE="\033[0;34m"
+C_GREEN="\033[0;32m"
+C_BOLD_WHITE="\033[1;37m"
+C_BOLD_YELLOW="\033[1;33m"
+C_BOLD_RED="\033[1;31m"
+C_BOLD_BLUE="\033[1;34m"
+C_BOLD_GREEN="\033[1;32m"
 C_RESET="\033[0m"
 
 # Function to print a debug message
@@ -50,6 +57,7 @@ function success() {
     echo -e "${C_DARK_WHITE}$(date +"%Y-%m-%d %H:%M:%S")${C_RESET} ${C_GREEN}[${C_RESET}${C_BOLD_GREEN}SUCCESS${C_RESET}${C_GREEN}]${C_RESET} ${C_GREEN}$1${C_RESET}"
 }
 
+# Function to trap exit signals
 function _exit_trap() {
     local exit_code=$?
     if [[ $exit_code -ne 0 ]]; then
@@ -61,8 +69,6 @@ function _exit_trap() {
     cd "$CSCRIPT_PATH"
     exit $exit_code
 }
-
-trap _exit_trap EXIT SIGINT SIGTERM ERR
 
 # Function to run a command
 function __run() {
@@ -319,9 +325,9 @@ function docker_network_up() {
     if ! __docker_network_exists "$NETWORK_NAME"; then
         info "Creating network: $NETWORK_NAME..."
         __run docker network create ${FARGS[@]} || {
-                err "Failed to create network: $NETWORK_NAME"
-                return 1
-            }
+            err "Failed to create network: $NETWORK_NAME"
+            return 1
+        }
         success "Network: $NETWORK_NAME created successfully."
         return 0
     else
@@ -343,12 +349,12 @@ function docker_network_down() {
         mapfile -t _endpointNames < <(docker network inspect "$_network" --format="{{range .Containers}}{{.Name}} {{end}}" | sed 's/ /\n/g')
         for _endpointName in "${_endpointNames[@]}"; do
             if [ -z "$_endpointName" ]; then
-            continue
+                continue
             fi
             info "Disconnecting network: $_network from endpoint: $_endpointName..."
             __run docker network disconnect --force "$_network" "$_endpointName" || {
-            err "Failed to disconnect network: $_network from endpoint: $_endpointName"
-            return 1
+                err "Failed to disconnect network: $_network from endpoint: $_endpointName"
+                return 1
             }
         done
         info "Trying to remove network: $_network..."
@@ -410,9 +416,9 @@ function docker_service_up() {
     if ! __docker_service_exists "$SERVICE_NAME"; then
         info "Creating service: $SERVICE_NAME..."
         __run docker service create ${FARGS[@]} || {
-                err "Failed to create service: $SERVICE_NAME"
-                return 1
-            }
+            err "Failed to create service: $SERVICE_NAME"
+            return 1
+        }
         success "Service: $SERVICE_NAME created successfully."
         return 0
     else
@@ -956,15 +962,6 @@ function __build_arg() {
 }
 
 # This function builds the arguments to be passed to the docker run command
-function _env_arg() {
-    local ENV_NAME="$1"
-    local ENV_VALUE="$2"
-    if [ -n "$ENV_VALUE" ]; then
-        echo "--env ${ENV_NAME}=${ENV_VALUE}"
-    fi
-}
-
-# This function builds the arguments to be passed to the docker run command
 function __build_args() {
     local ARGS=()
     ARGS+=("$(__build_arg APP_USER ${USER})")
@@ -975,16 +972,26 @@ function __build_args() {
 }
 
 # This function builds the arguments to be passed to the docker run command
-function _env_args() {
+function __env_arg() {
+    local ENV_NAME="$1"
+    local ENV_VALUE="$2"
+    if [ -n "$ENV_VALUE" ]; then
+        echo "--env ${ENV_NAME}=${ENV_VALUE}"
+    fi
+}
+
+# This function builds the arguments to be passed to the docker run command
+function __env_args() {
     local ARGS=()
-    ARGS+=("$(_env_arg LANG ${LANG})")
-    ARGS+=("$(_env_arg TZ ${TIMEZONE})")
+    ARGS+=("$(__env_arg LANG ${LANG})")
+    ARGS+=("$(__env_arg TZ ${TIMEZONE})")
     echo "${ARGS[@]}"
 }
 
-function __debug() {
+# This function outputs the debug flag if $DEBUG is set to true
+function __debug_flag() {
     if [ "$DEBUG" == true ]; then
-        echo -ne "--debug "
+        echo -ne "--debug"
     fi
 }
 
@@ -998,6 +1005,9 @@ function main() {
         case $SUBACTION in
         build)
             __run docker container prune -f || return 1
+            docker_containers_remove --filter label=com.docker.stack.namespace=opendevin || return 1
+            docker_images_remove --filter label=com.docker.stack.namespace=opendevin || return 1
+            docker_networks_down --filter label=com.docker.stack.namespace=opendevin || return 1
             # if __docker_image_exists "localhost:5000/opendevin-builder:latest"; then
             #     debug "Removing old base image from registry..."
             #     __run docker image rm "localhost:5000/opendevin-builder:latest" || return 1
@@ -1008,13 +1018,13 @@ function main() {
             # fi
             __run docker image prune -f || return 1
             docker_network_up \
-                 --label=com.docker.stack.namespace="opendevin" \
-                 --driver=overlay \
-                 --subnet=172.20.0.0/16 \
-                 --ip-range=172.20.0.0/24 \
-                 --gateway=172.20.0.254 \
-                 --attachable \
-                 opendevin_net || return 1 
+                --label=com.docker.stack.namespace="opendevin" \
+                --driver=overlay \
+                --subnet=172.20.0.0/16 \
+                --ip-range=172.20.0.0/24 \
+                --gateway=172.20.0.254 \
+                --attachable \
+                opendevin_net || return 1
             info "Building base image..."
             __run docker build \
                 --file "./docker/Dockerfile.builder" \
@@ -1037,12 +1047,21 @@ function main() {
                 --volume "/var/run/docker.sock:/var/run/docker.sock" \
                 --label "com.docker.stack.namespace=opendevin" \
                 localhost:5000/opendevin-runtime:latest \
-                build $(__debug) || return 1
+                build $(__debug_flag) || return 1
             success "OpenDevin runtime image built successfully."
             docker_container_commit "opendevin-prod" "localhost:5000/opendevin-runtime:latest" || return 1
+            docker_network_down "opendevin_net" || return 1
             ;;
         up)
             prep_data "./docker/data" || return 1
+            docker_network_up \
+                --label=com.docker.stack.namespace="opendevin" \
+                --driver=overlay \
+                --subnet=172.20.0.0/16 \
+                --ip-range=172.20.0.0/24 \
+                --gateway=172.20.0.254 \
+                --attachable \
+                opendevin_net || return 1
             docker_stack_deploy --compose-file "./docker/bb-stack.prod.yml" "opendevin" || return 1
             ;;
         down)
@@ -1083,7 +1102,7 @@ function main() {
                 --gateway=172.19.0.254 \
                 --attachable \
                 docker_manager || return 1
-            docker_stack_deploy --compose-file "./docker/bb-stack.manager.yml" "docker_manager"  || return 1
+            docker_stack_deploy --compose-file "./docker/bb-stack.manager.yml" "docker_manager" || return 1
             ;;
         down)
             docker_stack_down "docker_manager" || return 1
@@ -1103,5 +1122,6 @@ function main() {
     esac
 }
 
+trap _exit_trap EXIT SIGINT SIGTERM ERR
 parse_args "$@"
 main
