Update manual

diff --git a/opendevin b/opendevin
--- a/opendevin
+++ b/opendevin
@@ -7,66 +7,54 @@ set -Eeo pipefail
 DEBUG=${DEBUG:-false}
 ACTION=${ACTION:-}
 SUBACTION=${SUBACTION:-}
-WORKDIR=${WORKDIR:-./workdir}
+WORKDIR=${WORKDIR:-./app}
 LANG=${LANG:-}
 TIMEZONE=${TIMEZONE:-}
-GOSU_VERSION=${GOSU_VERSION:-}
-NODE_VERSION=${NODE_VERSION:-}
-NVM_VERSION=${NVM_VERSION:-}
-YARN_VERSION=${YARN_VERSION:-}
-PYTHON_VERSION=${PYTHON_VERSION:-}
 BARGS=""
-# CSCRIPT=$(readlink -f "$0")
 CSCRIPT_DIR=$(dirname "$0")
-# shellcheck disable=SC2206
-# CARGS=($*)
+
+# Colors
+C_DARK_WHITE="\033[0;30m"
+C_WHITE="\033[0;37m";       C_YELLOW="\033[0;33m";
+C_RED="\033[0;31m";         C_BLUE="\033[0;34m";            C_GREEN="\033[0;32m"
+C_BOLD_WHITE="\033[1;37m";  C_BOLD_YELLOW="\033[1;33m";     C_BOLD_RED="\033[1;31m"
+C_BOLD_BLUE="\033[1;34m";   C_BOLD_GREEN="\033[1;32m"
+C_RESET="\033[0m"
 
 # Function to print a debug message
 function debug() {
     if [ "$DEBUG" = true ]; then
-        local C_WHITE="\033[0;37m"
-        local C_BOLD_WHITE="\033[1;37m"
-        local C_RESET="\033[0m"
-        echo -e "${C_BOLD_WHITE}DEBUG: ${C_RESET}${C_WHITE}$1${C_RESET}" >&2
+        echo -e "${C_DARK_WHITE}$(date +"%Y-%m-%d %H:%M:%S")${C_RESET} ${C_WHITE}[${C_RESET}${C_BOLD_WHITE}DEBUG   ${C_RESET}${C_WHITE}]${C_RESET} ${C_WHITE}$1${C_RESET}" >&2
     fi
 }
 
 # function to print a warning message
 function warn() {
-    local C_YELLOW="\033[0;33m"
-    local C_BOLD_YELLOW="\033[1;33m"
-    local C_RESET="\033[0m"
-    echo -e "${C_BOLD_YELLOW}WARNING: ${C_RESET}${C_YELLOW}$1${C_RESET}" >&2
+    echo -e "${C_DARK_WHITE}$(date +"%Y-%m-%d %H:%M:%S")${C_RESET} ${C_YELLOW}[${C_RESET}${C_BOLD_YELLOW}WARNING${C_RESET}${C_YELLOW}]${C_RESET} ${C_YELLOW}$1${C_RESET}" >&2
 }
 
 # function to print an error message
 function err() {
-    local C_RED="\033[0;31m"
-    local C_BOLD_RED="\033[1;31m"
-    local C_RESET="\033[0m"
-    echo -e "${C_BOLD_RED}ERROR: ${C_RESET}${C_RED}$1${C_RESET}" >&2
+    echo -e "${C_DARK_WHITE}$(date +"%Y-%m-%d %H:%M:%S")${C_RESET} ${C_RED}[${C_RESET}${C_BOLD_RED}ERROR  ${C_RESET}${C_RED}]${C_RESET} ${C_RED}$1${C_RESET}" >&2
 }
 
 # Function to print an info message
 function info() {
-    local C_BLUE="\033[0;34m"
-    local C_BOLD_BLUE="\033[1;34m"
     local C_RESET="\033[0m"
-    echo -e "${C_BOLD_BLUE}INFO: ${C_RESET}${C_BLUE}$1${C_RESET}"
+    echo -e "${C_DARK_WHITE}$(date +"%Y-%m-%d %H:%M:%S")${C_RESET} ${C_BLUE}[${C_RESET}${C_BOLD_BLUE}INFO   ${C_RESET}${C_BLUE}]${C_RESET} ${C_BLUE}$1${C_RESET}"
 }
 
 # Function to print a success message
 function success() {
-    local C_GREEN="\033[0;32m"
-    local C_BOLD_GREEN="\033[1;32m"
     local C_RESET="\033[0m"
-    echo -e "${C_BOLD_GREEN}SUCCESS: ${C_RESET}${C_GREEN}$1${C_RESET}"
+    echo -e "${C_DARK_WHITE}$(date +"%Y-%m-%d %H:%M:%S")${C_RESET} ${C_GREEN}[${C_RESET}${C_BOLD_GREEN}SUCCESS${C_RESET}${C_GREEN}]${C_RESET} ${C_GREEN}$1${C_RESET}"
 }
 
+# Function to handle exit traps
 function _exit_trap() {
     local exit_code=$?
     if [[ $exit_code -ne 0 ]]; then
-        err "Error: Process exited with status code: $exit_code"
+        err "Process exited with status code: $exit_code"
     fi
     unset BUILDKIT_PROGRESS
     cd "$CSCRIPT_DIR"
@@ -75,11 +63,18 @@ function _exit_trap() {
 
 trap _exit_trap EXIT SIGINT SIGTERM ERR
 
+# Function to run a command
 function __run() {
     debug "Running command: $*"
-    eval "$*" || {
-        return $?
-    }
+    if [ "$DEBUG" = true ]; then
+        eval "$*" || {
+            return $?
+        }
+    else
+        eval "$* >/dev/null 2>&1" || {
+            return $?
+        }
+    fi
 }
 
 function __safe_rmdir() {
@@ -89,12 +84,12 @@ function __safe_rmdir() {
             sudo chown -R $(whoami) "$DIR"
             sudo chmod -R u+rww "$DIR"
             sudo rm -rfv "$DIR" || {
-                echo "Failed to remove directory $DIR"
+                err "Failed to remove directory $DIR"
                 return 1
             }
         }
     else
-        echo "Directory $DIR does not exist"
+        warning "Directory $DIR does not exist"
         return 0
     fi
 }
@@ -629,55 +624,60 @@ function reset_data() {
     fi
 }
 
+# This function prints the usage information.
 function usage() {
     local MYACTION="$1"
     shift 1 || true
     local MYSUBACTION="$1"
     shift 1 || true
-    echo "opendevin - A script to manage the OpenDevin project"
+    echo -e "${C_BOLD_YELLOW}-----------------------------------------------------------------------------------${C_RESET}"
+    echo -e "  ${C_BOLD_WHITE}OpenDevin${C_RESET} - Your superpowered AI coding assistant"
+    echo -e "${C_BOLD_YELLOW}-----------------------------------------------------------------------------------${C_RESET}"
     echo ""
-    echo "Usage: $0 <action> <subaction> [options] [args]"
+    echo -e "  ${C_BOLD_WHITE}Usage${C_RESET}"
     echo ""
-    echo "  Global Options:"
+    echo -e "    $0 <action> <subaction> [options] [arguments]"
     echo ""
-    echo "    -h, --help:     Show this help message"
-    echo "    -d, --debug:    Enable debug mode (prints a lot of spam used for debugging purposes"
-    echo "                    use with caution)"
+    echo -e "  ${C_BOLD_WHITE}Global Options${C_RESET}"
+    echo ""
+    echo "    --help        Show this help message, and exit"
+    echo "    --debug       Enable debug mode"
     echo ""
     case "$MYACTION" in
     gen)
         case "$MYSUBACTION" in
         build)
-            echo "  Options (used by build action):"
+            echo -e "  ${C_BOLD_WHITE}Options${C_RESET}"
             echo ""
-            echo "    -w, --workdir:          The working directory to mount in the container"
-            echo "    -l, --language:         The locale language"
-            echo "    -t, --timezone:         The timezone"
+            echo "    -l, --language          The locale language"
+            echo "    -t, --timezone          The timezone"
             echo ""
             ;;
         up)
-            echo "  Options (used by up action):"
+            echo -e "  ${C_BOLD_WHITE}Options${C_RESET}"
             echo ""
-            echo "   No arguments yet"
+            echo "    No options for this action."
             echo ""
             ;;
         down)
-            echo "  Options (used by down action):"
+            echo -e "  ${C_BOLD_WHITE}Options${C_RESET}"
             echo ""
-            echo "    No arguments yet"
+            echo "    No options for this action."
             echo ""
             ;;
         shell)
-            echo "  Options (used by shell action):"
+            echo -e "  ${C_BOLD_WHITE}Options${C_RESET}"
             echo ""
-            echo "    No arguments yet"
+            echo "    -w, --workdir           The working directory"
             echo ""
             ;;
         *)
-            echo "  Sub-Actions (required):"
+            echo -e "  ${C_BOLD_WHITE}Sub-Actions (required)${C_RESET}"
             echo ""
-            echo "    up:     Bring up the opendevin stack"
-            echo "    down    Bring down the opendevin stack"
+            echo "    build     Build the OpenDevin runtime."
+            echo "    up        Bring up the OpenDevin Application stack"
+            echo "    down      Bring down the OpenDevin Application stack"
+            echo "    shell     Start a shell session in the OpenDevin runtime container"
             echo ""
             ;;
         esac
@@ -685,44 +685,46 @@ function usage() {
     manager)
         case "$MYSUBACTION" in
         up)
-            echo "  Options (used by up action):"
+            echo -e "  ${C_BOLD_WHITE}Options${C_RESET}"
             echo ""
-            echo "    No arguments yet"
+            echo "    No options for this action."
             echo ""
             ;;
         down)
-            echo "  Options (used by down action):"
+            echo -e "  ${C_BOLD_WHITE}Options${C_RESET}"
             echo ""
-            echo "    No arguments yet"
+            echo "    No options for this action."
             echo ""
             ;;
         *)
-            echo "  Sub-Actions (required):"
+            echo -e "  ${C_BOLD_WHITE}Sub-Actions (required)${C_RESET}"
             echo ""
-            echo "    up:   Deploy the opendevin manager stack"
-            echo "    down: Remove the opendevin manager stack"
+            echo "    up        Deploy the opendevin manager stack"
+            echo "    down      Remove the opendevin manager stack"
             echo ""
             ;;
         esac
         ;;
     *)
-        echo "  Action (required):"
+        echo -e "  ${C_BOLD_WHITE}Action (required)${C_RESET}"
         echo ""
-        echo "    gen:         Manage the opendevin stack"
-        echo "    manager:     Manage the opendevin manager stack"
+        echo "    gen           Manage the opendevin stack"
+        echo "    manager       Manage the opendevin manager stack"
         echo ""
         ;;
     esac
-    echo "  Additional Arguments [args]:"
+    echo -e "  ${C_BOLD_WHITE}Additional Arguments${C_RESET}"
     echo ""
     echo "    Any additional arguments will be passed to the action command."
     echo ""
     echo "  For assistance with a specific action, use:"
     echo ""
     echo "    $0 <action> --help"
+    echo ""
     exit 0
 }
 
+# This function parses the arguments passed to the script
 function parse_args() {
     if [ $# -eq 0 ]; then
         usage
@@ -735,7 +737,7 @@ function parse_args() {
             usage gen
         fi
         if [[ ! "$1" =~ ^build|up|down|shell ]]; then
-            echo "Unknown sub-action: $1"
+            err "Unknown sub-action: $1"
             usage gen
         else
             SUBACTION="$1"
@@ -748,10 +750,6 @@ function parse_args() {
                 -h | --help)
                     usage gen build
                     break
-                    ;;
-                -w | --workdir)
-                    WORKDIR=$2
-                    shift 2
                     ;;
                 -l | --language)
                     LANG=$2
@@ -799,10 +797,6 @@ function parse_args() {
                     usage gen clean
                     break
                     ;;
-                -w | --workdir)
-                    WORKDIR=$2
-                    shift 2
-                    ;;
                 -d | --debug)
                     DEBUG=true
                     shift 1
@@ -848,7 +842,7 @@ function parse_args() {
             usage manager
         fi
         if [[ ! "$1" =~ ^up|down ]]; then
-            echo "Unknown sub-action: $1"
+            err "Unknown sub-action: $1"
             usage manager
         else
             SUBACTION="$1"
@@ -909,6 +903,7 @@ function parse_args() {
     done
 }
 
+# This function builds the arguments to be passed to the docker build command
 function __build_arg() {
     local ARG_NAME="$1"
     local ARG_VALUE="$2"
@@ -917,6 +912,7 @@ function __build_arg() {
     fi
 }
 
+# This function builds the arguments to be passed to the docker run command
 function _env_arg() {
     local ENV_NAME="$1"
     local ENV_VALUE="$2"
@@ -925,6 +921,7 @@ function _env_arg() {
     fi
 }
 
+# This function builds the arguments to be passed to the docker run command
 function __build_args() {
     local ARGS=()
     ARGS+=("$(__build_arg APP_USER ${USER})")
@@ -934,6 +931,7 @@ function __build_args() {
     echo "${ARGS[@]}"
 }
 
+# This function builds the arguments to be passed to the docker run command
 function _env_args() {
     local ARGS=()
     ARGS+=("$(_env_arg LANG ${LANG})")
@@ -941,6 +939,7 @@ function _env_args() {
     echo "${ARGS[@]}"
 }
 
+# This function is the main entry point for the script
 function main() {
     if [ "$DEBUG" = true ]; then
         export BUILDKIT_PROGRESS=plain
@@ -949,16 +948,16 @@ function main() {
     gen)
         case $SUBACTION in
         build)
-            __run docker container prune -f || true
+            __run docker container prune -f || return 1
             if __docker_image_exists "localhost:5000/opendevin-builder:latest"; then
-                info "Removing old base image from registry..."
+                debug "Removing old base image from registry..."
                 __run docker image rm "localhost:5000/opendevin-builder:latest" || return 1
             fi
             if __docker_image_exists "localhost:5000/opendevin-runtime:latest"; then
-                info "Removing old opendevin runtime image from registry..."
+                debug "Removing old opendevin runtime image from registry..."
                 __run docker image rm "localhost:5000/opendevin-runtime:latest" || return 1
             fi
-            info "Pruning old images..."
+            debug "Pruning old images..."
             __run docker image prune -f || return 1
             info "Building base image..."
             __run docker build \
@@ -1024,7 +1023,7 @@ function main() {
                 shell || return 1
             ;;
         *)
-            echo "Unknown sub-action: $SUBACTION"
+            err "Unknown sub-action: $SUBACTION"
             exit 1
             ;;
         esac
@@ -1044,22 +1043,22 @@ function main() {
             docker_stack_deploy --compose-file "./docker/bb-stack.manager.yml" "docker_manager"  || return 1
             ;;
         down)
-            docker_stack_down "docker_manager"
-            docker_networks_down --filter label=com.docker.stack.namespace=docker_manager
-            docker_swarm_leave
+            docker_stack_down "docker_manager" || return 1
+            docker_networks_down --filter label=com.docker.stack.namespace=docker_manager || return 1
+            docker_swarm_leave || return 1
             ;;
         *)
-            echo "Unknown sub-action: $SUBACTION"
-            exit 1
+            err "Unknown sub-action: $SUBACTION"
+            return 1
             ;;
         esac
         ;;
     *)
         echo "Unknown action: $ACTION"
-        exit 1
+        return 1
         ;;
     esac
 }
 
 parse_args "$@"
-main || true
+main
